---
title: "Tree Canopy - COVID death rate"
author: "Clarissa Boyajian"
date: "11/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(scipen = 999)

library(tidyverse)
library(lubridate)
library(janitor)
library(sf)
library(tmap)
library(patchwork)
```

```{r Read in data}
county_geom_raw <- st_read("map_data/counties.shp") 

tree_canopy_raw <- read_csv("tree_data/HPI-Individual-Indicators/HPI2_treecanopy.csv")

covid_raw_johnshopkins <- read.csv("covid_data/covid19cases_test.csv") # 2020-02-01 - 2021-11-18
covid_raw_latimes <- read.csv("covid_data/cdph-county-cases-deaths.csv") # 2020-02-01 - 2021-11-22
```

```{r Parameters}
county_region1 <- c("Butte", "Colusa", "El Dorado", "Glenn", "Lassen", "Modoc", 
                    "Nevada", "Placer", "Plumas", "Sacramento", "Shasta", 
                    "Sierra", "Siskiyou", "Sutter", "Tehama", "Yolo", "Yuba")
county_region2 <- c("Del Norte", "Humboldt", "Lake", "Mendocino", "Napa", 
                    "Sonoma", "Trinity")
county_region3 <- c("Alameda", "Contra Costa", "Marin", "San Francisco", 
                    "San Mateo", "Santa Clara", "Solano") 
county_region4 <- c("Amador", "Calaveras", "Madera", "Mariposa", "Merced", 
                     "Mono", "San Joaquin", "Stanislaus", "Tuolumne")
county_region5 <- c("Monterey", "San Benito", "San Luis Obispo", 
                    "Santa Barbara", "Santa Cruz", "Ventura")
county_region6 <- c("Fresno", "Inyo", "Kern", "Kings", "Tulare")
county_region7 <- c("Riverside", "San Bernardino")
county_region8 <- c("Los Angeles")
county_region9 <- c("Orange")
county_region10 <- c("Imperial", "San Diego")
```

## Data Wrangling

```{r Wrangling geometry data}
county_geom <- 
  county_geom_raw %>% 
  clean_names() %>% 
  rename(county_name = name) %>% 
  mutate(county_region = case_when(county_name %in% county_region1 ~ "01",
                                   county_name %in% county_region2 ~ "02",
                                   county_name %in% county_region3 ~ "03",
                                   county_name %in% county_region4 ~ "04",
                                   county_name %in% county_region5 ~ "05",
                                   county_name %in% county_region6 ~ "06",
                                   county_name %in% county_region7 ~ "07",
                                   county_name %in% county_region8 ~ "08",
                                   county_name %in% county_region9 ~ "09",
                                   county_name %in% county_region10 ~ "10"),
         county_region_name = case_when(county_name %in% county_region1 ~ "Superior California",
                                        county_name %in% county_region2 ~ "North Coast",
                                        county_name %in% county_region3 ~ "San Francisco Bay Area",
                                        county_name %in% county_region4 ~ "Northern San Joaquin Valley",
                                        county_name %in% county_region5 ~ "Central Coast",
                                        county_name %in% county_region6 ~ "Southern San Joaquin Valley",
                                        county_name %in% county_region7 ~ "Inland Empire",
                                        county_name %in% county_region8 ~ "Los Angeles County",
                                        county_name %in% county_region9 ~ "Orange County",
                                        county_name %in% county_region10 ~ "San Diego - Imperial")) %>% 
  mutate(county_region_name = fct_relevel(county_region_name, levels = c("Superior California", "North Coast", "San Francisco Bay Area", "Northern San Joaquin Valley", "Central Coast", "Southern San Joaquin Valley", "Inland Empire", "Los Angeles County", "Orange County", "San Diego - Imperial")))
```

```{r Wrangling tree data}
tree_data <- 
  tree_canopy_raw %>% 
  clean_names() %>% 
  select(-c(indicator, treecanopy_n, treecanopy_d, notes) # remove empty columns
        ) %>% 
  group_by(county_name) %>% 
  summarise(county_treecanopy_pct = mean(treecanopy_pct))
```

```{r Wrangling covid data, eval=FALSE}
covid_data_johnshopkins <- 
  covid_raw_johnshopkins %>% 
  clean_names() %>% 
    filter(area_type == "County", # remove CA row
         !grepl(c("Unknow|Out of state|Alpine"), area) # remove county not in tree data and non-counties
         ) %>% 
  rename(county_name = area) %>% 
  mutate(date = as.Date(ymd(date)))
```

```{r}
covid_data_latimes <- 
  covid_raw_latimes %>% 
  clean_names() %>% 
  filter(!grepl(c("Alpine"), county)) %>% # remove county not in tree data and non-counties
  select(-fips) %>% # remove column contained in counties geom data
  rename(county_name = county) %>% 
  mutate(date = as.Date(ymd(date)))
```


## Analysis


```{r Basic analysis covid data}
covid_county_average <- 
  covid_data_latimes %>% 
  group_by(county_name) %>% 
  summarise(population_av = mean(population),
            confirmed_cases_av = mean(confirmed_cases),
            reported_deaths_av = mean(reported_deaths)) %>% 
  mutate(deaths_per_case_pct = reported_deaths_av / confirmed_cases_av,
         deaths_per_pop_pct = reported_deaths_av / population_av)
```


```{r Combining data}
full_data_combined <- 
  left_join(x = covid_data_latimes, y = tree_data, by = "county_name") %>% 
  left_join(y = county_geom, by = "county_name")

tree_data_geom <- 
  left_join(x = tree_data, y = county_geom, by = "county_name") %>% 
  st_as_sf()

covid_county_average_geom <- 
  left_join(x = covid_county_average, y = county_geom, by = "county_name") %>% 
  st_as_sf()
```


## Initial viz

```{r}
tm_shape(tree_data_geom) +
  tm_borders(col = "black", alpha = .65) +
  tm_fill(col = "county_treecanopy_pct",
          style = "cont", 
          n = 5,
          palette ="viridis")

tm_shape(covid_county_average_geom) +
  tm_borders(col = "black", alpha = .65) +
  tm_fill(col = "deaths_per_case_pct",
          style = "cont", 
          n = 5,
          palette ="viridis")
```



## Basic Analysis and viz

```{r Covid basic analysis}
covid_county_region_month_average <- 
  covid_county_average_geom %>% 
  group_by(county_region_name, county_region) %>% 
  summarise(county_region_monthly_death_av = mean(reported_deaths_av),
            county_region_monthly_positive_test_av = mean(confirmed_cases_av))
  
  

```

```{r Tree basic analysis}
tree_county_region <- 
  tree_data_geom %>% 
  group_by(county_region_name, county_region) %>% 
  summarise(county_region_tree_pct = mean(county_treecanopy_pct))
```


```{r Plot basic analysis}
covid_county_region_month_av_plot <- 
  ggplot(data = covid_county_region_month_average, 
         aes(x = county_region_monthly_death_av, 
             y = county_region_name, 
             fill = county_region_name)) +
  geom_col()+
  scale_fill_viridis_d()

tree_county_region_plot <- 
  ggplot(data = tree_county_region,
         aes(x = county_region_tree_pct,
             y = county_region_name,
             fill = county_region_name)) +
  geom_col() +
  scale_fill_viridis_d()

covid_county_region_month_av_plot / tree_county_region_plot +plot_layout(guides = "collect")
```


## Analysis

```{r Summary covid data}
covid_1yearsummary <- 
  covid_data_latimes %>%
  filter(date < "2021-02-01", # one column per county
         ) %>% 
  group_by(county_name) %>% 
  summarise(population_av = mean(population),
            confirmed_cases_av = mean(confirmed_cases),
            reported_deaths_av = mean(reported_deaths)) %>% 
  mutate(deaths_per_case_pct = reported_deaths_av / confirmed_cases_av,
         deaths_per_pop_pct = reported_deaths_av / population_av)
```

```{r Combine data}
covid_tree_1yearsummmary <- 
  left_join(covid_1yearsummary, tree_data, by = "county_name")
```

```{r}
ggplot(data = covid_tree_1yearsummmary, 
       aes(x = county_treecanopy_pct, 
           y = deaths_per_case_pct)) +
  geom_point()
```






```{r}
mod <- lm(county_treecanopy_pct ~ deaths_per_case_pct, data = covid_tree_1yearsummmary)

summary(mod)
```












### References
1. 
2. 
